### ISSUE TITLE
end } curly bracket is missing in docs. Can we change this to example api call for cURL tab?

### ISSUE THREAD

**Issue by harpreetvishnoi** [symblai/documentation#1]
https://docs.symbl.ai/docs/conversation-api/update-members

end } curly bracket is missing in docs. Can we change this to example api call for cURL tab?
```
curl --location --request PUT "https://api.symbl.ai/v1/conversations/$CONVERATION_ID/members/$MEMBER_ID" 
 --header 'Content-Type: application/json'
 --header "Authorization: Bearer $AUTH_TOKEN" 
 --data-raw '{
    "id": "'$MEMBER_ID'",
    "email": "john@example.com",
    "name": "John"
}'
```

**Comment by pema-s** [comment]
Hi @harpreetvishnoi 

Thanks for reporting this issue. We have made the changes as suggested by you. 

https://docs.symbl.ai/docs/conversation-api/update-members

Thanks for helping us make our docs better!
